Squashed commit of the following:
update 8 mai 2025
=================

- After switching from @tcl85 to @tcl86, it became apparent that there was a problem distinguishing an @b existing
  @tcl86 installation from the new @atl10 installation.
- To circumvent this and protect @tcl86, the distribution was renamed to @atl10, thus changing the @e visible interface
  to @b atl.
- The invisible interface (i.e., functions, variables, constants, etc.) remains untouched and thus binary compatible.
  - However, this will change in the future when \c atlsh becomes a standalone product.
- The following changes were made:
\verbatim
from                   | to
------------------     | ----------------
tclConfig.sh           | atlConfig.sh
tclsh                  | atlsh
tcltest                | atltest
include/tcl*.h         | include/atl/tcl*.h
lib/tcl8               | lib/atl1
lib/tcl8.6             | lib/atl1.0
bin/tclsh              | bin/atlsh
lib64/pkgconfig/tcl.pc | lib64/pkgconfig/atl.pc
lib64/libtclstub8.6.a  | lib64/libatlstub1.0.a
lib64/tclConfig.sh     | lib64/atlConfig.sh
lib64/libtcl8.6.so     | lib64/libatl1.0.so
share/man1/*.1         | share/atl/man1/*.1
share/man3/*.3         | share/atl/man3/*.3
share/mann/*.n         | share/atl/mann/*.n
TCLLIBPATH             | ATL_LIBPATH
TCL_LIBRARY            | ATL_LIBRARY
\endverbatim

update 5 mai 2025
=================

After switching from @tcl85 to @tcl86, the paralellization of @tcltest was complete.
- @zlib and @tclOO have also been removed.
- all \e sub-packages from \c pkgs were removed.
- Next, @NRE and @thread support will be removed.
- Once all this is complete, the @interp command will be replaced by a \b NEW technology.
- example: new massive parallel testing of the @tcl86 test suite.
\verbatim
...
PASS: dict.test
PASS: exec.test
PASS: expr.test
PASS: reg.test
PASS: socket.test
PASS: thread.test
PASS: interp.test
PASS: lmap.test
PASS: async.test
PASS: chanio.test
PASS: tcltest.test
PASS: main.test
PASS: clock.test
PASS: regexp.test
PASS: io.test
PASS: ioCmd.test
============================================================================
Testsuite summary for NHI1 10.0
============================================================================
============================================================================
...

real    1m30,248s
user    3m55,929s
sys     0m15,400s
\endverbatim

update 2 mai 2025
=================

- Testing @tcl85 with the @tcl86 test cases revealed that @tcl85 contains numerous serious (core) bugs that were only
  fixed in @tcl86.
- However, @tcl86 is now the problematic version with @NRE and @tclOO.
- An initial attempt to patch @tcl85 required importing a large amount of code from @tcl86.
- This raises the question of whether it even makes sense to patch @tcl85 towards @tcl86 when the end result is @tcl86 anyway.
- The strategy of starting with @tcl86 and removing everything unwanted seems more sensible to me, as it starts with a
  bug-free launch, which is then successively retested at each step.

diff --git a/bin/atltest b/bin/atltest
--- a/bin/atltest
+++ b/bin/atltest
@@ -9,8 +9,8 @@
 
 # atltest ..
 # 
-# This script is used to run the "tcltest" tool from the Makefile. 
-# The environment must be configured so that "tcltest" only has access 
+# This script is used to run the "atltest" tool from the Makefile. 
+# The environment must be configured so that "atltest" only has access 
 # to the data from the "build" and "source" directory.
 #
 # example :
@@ -23,23 +23,23 @@ abs_local_dir="${abs_local_path%/*}"
 abs_atlsh_dir="${abs_local_dir%/*}/atlsh"
 
 # get "abs_top_builddir"
-if [[ -f "${NHI1_abs_top_builddir:-NHI1_abs_top_builddir_UNKNOWN}/theATL/atlsh/unix/tclBuild.sh" ]] ; then
+if [[ -f "${NHI1_abs_top_builddir:-NHI1_abs_top_builddir_UNKNOWN}/theATL/atlsh/unix/atlBuild.sh" ]] ; then
   # get it from the "NHI1" environment (only as subproject)
   abs_atlsh_builddir="${NHI1_abs_top_builddir}/theATL/atlsh"
-elif [[ -f "$abs_atlsh_dir/unix/tclBuild.sh" ]] ; then
+elif [[ -f "$abs_atlsh_dir/unix/atlBuild.sh" ]] ; then
   # get it from "in-source" build
   abs_atlsh_builddir="$abs_atlsh_dir"
 else
-  echo "error: tclBuild.sh not found" 1>&2 ; exit 1
+  echo "error: atlBuild.sh not found" 1>&2 ; exit 1
 fi
 
 # source build environment - setup with "configure"
-# set: TCL_TOP_SRC_DIR TCL_TOP_BUILD_DIR LD_LIBRARY_PATH TCLLIBPATH TCL_LIBRARY
-source "$abs_atlsh_builddir/unix/tclBuild.sh"
+# set: TCL_TOP_SOURCE_DIR TCL_TOP_BUILD_DIR LD_LIBRARY_PATH ATL_LIBPATH ATL_LIBRARY
+source "$abs_atlsh_builddir/unix/atlBuild.sh"
 
-# if "tcltest" not already build → build it
-if [[ ! -f "$TCL_TOP_BUILD_DIR/unix/tcltest" ]] ; then
-  make --directory "$TCL_TOP_BUILD_DIR/unix" tcltest || exit 2
+# if "atltest" not already build → build it
+if [[ ! -f "$TCL_TOP_BUILD_DIR/unix/atltest" ]] ; then
+  make --directory "$TCL_TOP_BUILD_DIR/unix" atltest || exit 2
 fi
 
 #set -x
@@ -55,10 +55,11 @@ while true ; do
   for a in $first ; do
     [[ ! -f "$a" ]] && break
     f="$first"
+    d="${f%/*}"
     shift
-    set -- -file "${f##*/}" -testdir "${f%/*}" "$@"
+    set -- -file "${f##*/}" -testdir "$d" -tmpdir "${d/$TCL_TOP_SOURCE_DIR/$TCL_TOP_BUILD_DIR}" "$@"
     if (( justone )) ; then
-      set -- "$@" -verbose bpt
+      : set -- "$@" -verbose bpt
     fi
     break 2
   done
@@ -67,7 +68,8 @@ while true ; do
   for a in $last ; do
     [[ ! -f "$a" ]] && break
     f="$last"
-    set -- -file "${f##*/}" -testdir "${f%/*}" "${@:1:$(( $# - 1 ))}"
+    d="${f%/*}"
+    set -- -file "${f##*/}" -testdir "$d" -tmpdir "${d/$TCL_TOP_SOURCE_DIR/$TCL_TOP_BUILD_DIR}" "${@:1:$(( $# - 1 ))}"
     break 2
   done
 
@@ -75,6 +77,8 @@ while true ; do
 
 done
 
-exec "$TCL_TOP_BUILD_DIR/unix/tcltest" "$TCL_TOP_SRC_DIR/../tests/all.tcl" "$@"
+#ldd "$TCL_TOP_BUILD_DIR/unix/atltest"
+
+exec "$TCL_TOP_BUILD_DIR/unix/atltest" "$TCL_TOP_SOURCE_DIR/../tests/all.tcl" "$@"
 
 # vim: path+=../tests
